version: '3.7'

services:
  db:
    volumes:
      - '${PATH_REDIS:-dbdata}:/data/db'
    deploy:
      placement:
        constraints:
          - node.labels.type == db
  app:
    env_file: '${ENV_APP_FILE_PATH:-./server/configuration/environment/prod.env}'
    deploy:
      placement:
        constraints:
          - node.labels.type == app

networks:
  site_network:
    external: true
