version: '3.7'

services:
  db:
    image: redis:5
    container_name: redis.khemlabs
    volumes:
      - '${PATH_REDIS:-dbdata}:/data/db'
    restart: always
    networks:
      - site_network
  app:
    depends_on:
      - db
    build:
      context: ./
      args:
        SERVER_PORT: '${PORT:-3000}'
    image: 'khemlabs/khemlabs-site:${TAG:-latest}'
    container_name: app.khemlabs
    volumes:
      - '${PATH_APP:-appdata}:/app'
    restart: always
    networks:
      - site_network

volumes:
  dbdata:
  appdata:

networks:
  site_network:
    driver: overlay
